name: Yocto APP CI

on: [push]

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: robinraju/release-downloader@v1
        with:
          repository: 'arnew/yocto-ci-test'
          latest: true
          fileName: '*.sh.xz'
      - name: build
        run: |
          unxz *xz
          chmod +x poky*sh
          ./poky*sh -y -d sdk
          . sdk/env*
          cmake .
          make
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: classifier

