name: Yocto APP CI

on: [push]

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: robinraju/release-downloader@v1
        with:
          repository: 'arnew/yocto-ci-test'
          latest: true
          fileName: '*.sh'
      - name: build
        run: |
          chmod +x poky*sh
          ./poky*sh -y -d sdk
          . sdk/env*
          cmake .
          make

